#!/bin/bash

sudo apt update
sudo apt upgrade
sudo apt install vim -y
sudo apt install i3 -y
sudo apt install python3-pip -y
sudo apt install autojump
sudo apt install git

pip3 install ipython -y
echo "alias apt='apt -y'" >> ~/.bashrc
echo ". /usr/share/autojump/autojump.sh" >> ~/.bashrc


